In [1]:
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

In [2]:
delia_ticker = "DELIA.OL"

### Financial statement analysis

In [7]:
income = yf.Ticker(delia_ticker).financials

income.head()

,2025-12-31,2024-12-31,2023-12-31,2022-12-31
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.00
Tax Rate For Calcs,2.325100e-01,2.442200e-01,3.186410e-01,0.22
Normalized EBITDA,6.977000e+07,1.196200e+07,4.774000e+06,1024000.00
Net Income From Continuing Operation Net Minority Interest,4.918900e+07,2.806000e+06,3.567000e+06,410000.00
Reconciled Depreciation,2.611000e+06,1.431000e+06,9.050000e+05,393000.00

Key ratios we want to find: 
- Gross profit margin
- Ebit / Revenue
- Ebitda / Revenue

In [14]:
income_ratios = {
    'Gross profit margin, %': (income.loc['Gross Profit'] / income.loc['Total Revenue'] * 100).round(2),
    'Ebitda / Revenue, %': (income.loc['EBITDA'] / income.loc['Total Revenue'] * 100).round(2),
    'Ebit / Revenue, %': (income.loc['EBIT'] / income.loc['Total Revenue'] * 100).round(2),
}

income_ratios

{'Gross profit margin, %': 2025-12-31    32.97
 2024-12-31    32.91
 2023-12-31    36.52
 2022-12-31    24.26
 dtype: float64,
 'Ebitda / Revenue, %': 2025-12-31    10.93
 2024-12-31     4.50
 2023-12-31     4.51
 2022-12-31     1.93
 dtype: float64,
 'Ebit / Revenue, %': 2025-12-31    10.52
 2024-12-31     3.96
 2023-12-31     3.65
 2022-12-31     1.19
 dtype: float64}

In [15]:
income_df = pd.DataFrame(income_ratios)
income_df

            Gross profit margin, %  Ebitda / Revenue, %  Ebit / Revenue, %
2025-12-31                   32.97                10.93              10.52
2024-12-31                   32.91                 4.50               3.96
2023-12-31                   36.52                 4.51               3.65
2022-12-31                   24.26                 1.93               1.19

### Balance sheet analysis

In [25]:
balance_sheet = yf.Ticker(delia_ticker).balance_sheet

print(balance_sheet.to_string())

                                                         2025-12-31   2024-12-31  2023-12-31  2022-12-31  2021-12-31
Treasury Shares Number                                      76895.0          NaN         NaN         NaN         NaN
Ordinary Shares Number                                    5383105.0    4733105.0   4733105.0   4733105.0         NaN
Share Issued                                              5460000.0    4733105.0   4733105.0   4733105.0         NaN
Net Debt                                                        NaN   15793000.0         NaN         NaN         NaN
Total Debt                                              117475000.0   25490000.0   1833000.0   1023000.0         NaN
Tangible Book Value                                     387153000.0   48603000.0  53308000.0  23876000.0         NaN
Invested Capital                                        493279000.0   71561000.0  54229000.0  24533000.0         NaN
Working Capital                                         380063000.0   44924000.0  50120000.0  22267000.0         NaN
Net Tangible Assets                                     387153000.0   48603000.0  53308000.0  23876000.0         NaN
Capital Lease Obligations                                11349000.0    2532000.0    912000.0    366000.0         NaN
Common Stock Equity                                     387153000.0   48603000.0  53308000.0  23876000.0         NaN
Total Capitalization                                    387395000.0   48983000.0  53932000.0  24321000.0         NaN
Total Equity Gross Minority Interest                    387153000.0   48603000.0  50670000.0  22588000.0         NaN
Minority Interest                                               NaN          0.0  -2638000.0  -1288000.0   -569000.0
Stockholders Equity                                     387153000.0   48603000.0  53308000.0  23876000.0         NaN
Other Equity Interest                                           NaN      -1000.0         NaN         NaN         NaN
Treasury Stock                                              77000.0          0.0         NaN         NaN         NaN
Retained Earnings                                        12978000.0  -34907000.0   5049000.0   3442000.0         NaN
Additional Paid In Capital                              366753000.0   79870000.0  44898000.0  17604000.0         NaN
Capital Stock                                             5460000.0    4069000.0   3396000.0   2830000.0         NaN
Common Stock                                              5460000.0    4069000.0   3396000.0   2830000.0         NaN
Total Liabilities Net Minority Interest                 210221000.0   66973000.0  16047000.0   4734000.0         NaN
Total Non Current Liabilities Net Minority Interest       9796000.0    1744000.0   1062000.0    570000.0         NaN
Other Non Current Liabilities                               -1000.0          NaN         NaN         NaN         NaN
Non Current Deferred Taxes Liabilities                     166000.0      32000.0     69000.0         0.0         NaN
Long Term Debt And Capital Lease Obligation               8998000.0    1712000.0    993000.0    570000.0         NaN
Long Term Capital Lease Obligation                        8756000.0    1332000.0    369000.0    125000.0         NaN
Long Term Debt                                             242000.0     380000.0    624000.0    445000.0         NaN
Long Term Provisions                                       633000.0          NaN         NaN         NaN         NaN
Current Liabilities                                     200425000.0   65229000.0  14985000.0   4164000.0         NaN
Other Current Liabilities                                25281000.0          NaN      1000.0     -1000.0      1000.0
Current Debt And Capital Lease Obligation               108477000.0   23778000.0    840000.0    453000.0         NaN
Current Capital Lease Obligation                          2593000.0    1200000.0    543000.0    241000.0         NaN
Current Debt                                            105884000.0   22578000.0    297000.0    212000.0         NaN
Pensionand Other Post Retirement Benefit Plans Current          NaN    3988000.0   1357000.0   1190000.0   1128000.0
Payables                                                 85917000.0   27485000.0   9320000.0   2119000.0         NaN
Other Payable                                            19250000.0    8578000.0         NaN         NaN         NaN
Total Tax Payable                                         9234000.0    2528000.0    863000.0     14000.0         NaN
Accounts Payable                                         57433000.0   16379000.0   8457000.0   2105000.0         NaN
Total Assets                                            597374000.0  115576000.0  66717000.0  27322000.0         NaN
Total Non Current Assets                                 16886000.0    5424000.0   1612000.0    890000.0         NaN
Other Non Current Assets                                     1000.0          NaN         NaN         NaN         NaN
Non Current Deferred Taxes Assets                          224000.0    1884000.0         0.0     38000.0         NaN
Net PPE                                                  16661000.0    3309000.0   1517000.0    520000.0         NaN
Accumulated Depreciation                                 -1303000.0    -873000.0   -568000.0   -392000.0         NaN
Gross PPE                                                17964000.0    4182000.0   2085000.0    912000.0         NaN
Other Properties                                         16661000.0          NaN         NaN         NaN         NaN
Machinery Furniture Equipment                             8847000.0    2054000.0   1212000.0    539000.0         NaN
Buildings And Improvements                                9117000.0    2128000.0    873000.0    373000.0         NaN
Properties                                                      0.0          0.0         0.0         0.0         NaN
Current Assets                                          580488000.0  110153000.0  65105000.0  26431000.0         NaN
Restricted Cash                                             54000.0     222000.0    210000.0     54000.0         NaN
Prepaid Assets                                           33150000.0    5870000.0   1886000.0   3895000.0         NaN
Inventory                                               191489000.0   62678000.0  24242000.0   5367000.0         NaN
Inventories Adjustments Allowances                              NaN          0.0         0.0         0.0         0.0
Finished Goods                                          191489000.0   62678000.0  24242000.0   5367000.0         NaN
Other Receivables                                        16562000.0    2664000.0         NaN         NaN         NaN
Accounts Receivable                                      75550000.0   31554000.0   8721000.0   1696000.0         NaN
Allowance For Doubtful Accounts Receivable                      0.0          0.0         0.0         0.0         NaN
Gross Accounts Receivable                                75550000.0   31554000.0   8721000.0   1696000.0         NaN
Cash Cash Equivalents And Short Term Investments        263683000.0    7165000.0  30046000.0  15419000.0         NaN
Cash And Cash Equivalents                               263683000.0    7165000.0  30046000.0  15419000.0         NaN
Cash Financial                                          263683000.0    7165000.0  30046000.0  15419000.0         NaN

In [39]:
balance_sheet_ratios = pd.DataFrame({
    'Current ratio': balance_sheet.loc['Current Assets'] / balance_sheet.loc['Current Liabilities'],
    'Quick ratio': (balance_sheet.loc['Cash And Cash Equivalents'] + balance_sheet.loc['Accounts Receivable']) / balance_sheet.loc['Current Liabilities'],
    'Equity ratio': balance_sheet.loc['Stockholders Equity'] / balance_sheet.loc['Total Assets'],
    'Debt to Equity ratio': balance_sheet.loc['Total Liabilities Net Minority Interest'] / balance_sheet.loc['Stockholders Equity']
}
).round(3)

balance_sheet_ratios

            Current ratio  Quick ratio  Equity ratio  Debt to Equity ratio
2025-12-31          2.896        1.693         0.648                 0.543
2024-12-31          1.689        0.594         0.421                 1.378
2023-12-31          4.345        2.587         0.799                 0.301
2022-12-31          6.348        4.110         0.874                 0.198
2021-12-31            NaN          NaN           NaN                   NaN

In [50]:
print(f"ROE: {income.loc['Net Income'] / balance_sheet.loc['Stockholders Equity']*100}%")
print(f"Asset Turnover Ratio: {income.loc['Total Revenue'] / balance_sheet.loc['Total Assets']}")

ROE: 2021-12-31          NaN
2022-12-31     1.717206
2023-12-31     6.691303
2024-12-31     5.773306
2025-12-31    12.705313
Freq: YE-DEC, dtype: float64%
Asset Turnover Ratio: 2021-12-31         NaN
2022-12-31    1.937486
2023-12-31    1.587272
2024-12-31    2.301282
2025-12-31    1.068495
Freq: YE-DEC, dtype: float64